---
baseurl: "/"
languageCode: "en-us"
theme: "hello-friend-ng"

params:
    dateform       : "Jan 2, 2006"
    dateformShort  : "Jan 2"
    dateformNum    : "2006-01-02"
    dateformNumTime: "2006-01-02 15:04 -0700"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts: false

    # Metadata mostly used in document's head
    description: "My new homepage or blog"
    keywords: "homepage, blog"
    images: [""]

    # Directory name of your blog content (default is `content/posts`)
    contentTypeName: "posts"

    # Default theme "light" or "dark"
    defaultTheme: "dark"

    social:
      - name: "twitter"
        url: "https://twitter.com/dbarrosop"
      - name: "github"
        url: "https://github.com/dbarrosop"
      - name: "linkedin"
        url: "https://linkedin.com/dbarrosop"
      - name: "email"
        url: "mailto:dbarrosop@dravetech.com"

    customCSS:
      - /css/callout.css

languages:
    en:
        title: "nornir.tech"
        subtitle: "News and information about nornir's projects"
        keywords: "nornir automation networking programming python golang"
        copyright: "Nornir"
        readOtherPosts: "Read other posts"

        params:
            logo:
                logoText: "nornir.tech"
                logoHomeLink: "/"
                # or
                #
                # path: "/img/your-example-logo.svg"
                # alt: "Your example logo alt text"
                #
menu:
    main:
      - identifier: "projects"
        name      : "projects"
        url       : "/projects"
        weight    : "1"
      - identifier: "posts"
        name      : "posts"
        url       : "/posts"
        weight    : "2"
      - identifier: "about"
        name      : "about"
        url       : "/about"
        weight    : "3"
      - identifier: "sponsor"
        name      : "sponsor"
        url       : "/sponsor"
        weight    : "4"
      - identifier: "tags"
        name      : "tags"
        url       : "/tags"
        weight    : "5"

taxonomies:
    tag: tags

permalinks:
    posts: /:year/:month/:day/:title/
